using System;
using Microsoft.CodeAnalysis;

namespace NoesisToolkit.CodeGen;

static class Output
{
    static readonly DiagnosticDescriptor DuplicateHintName = new(
        "NTK0001",
        "Duplicate generated file name",
        "{0}",
        "NoesisToolkit",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public static void Header(CodeWriter w, bool nullable = true)
    {
        w.Line("// <auto-generated/>");
        if (nullable)
            w.Line("#nullable enable");
        w.Line();
    }

    /// <summary>Adds a generated file, reporting a hint-name collision instead of swallowing it.</summary>
    public static void Add(SourceProductionContext spc, string hintName, string source)
    {
        try
        {
            spc.AddSource(hintName, source);
        }
        catch (ArgumentException)
        {
            spc.ReportDiagnostic(
                Diagnostic.Create(
                    DuplicateHintName,
                    Location.None,
                    $"Two inputs both generate '{hintName}'; only the first was emitted."
                )
            );
        }
    }
}
